Fixed program logging issues
vadim0x60/nl2ml-codex pull request #5
Opened 2023-10-13 09:38 UTC by vadim0x60

Such as:
- A long is_already_solved check when the program doesn't even exist yet
- solutions_dir not being found due to current workdir schenanigans

2023-10-13 14:40 UTC, Anastasiia-Grishina commented on seidr/github.py
Line 39 in `github.py`: why don't we log a link to the corresponding commit?

```
    commit_url = repo.remotes.origin.url + "/commit/" + repo.head.commit.hexsha
    commit_url = 'https://' + commit_url[commit_url.find('@github.com') + 1:]
    logging.info(f'Tried to push updates to git repo.\n'
                 f'See commit at {commit_url}. \n'
                 f'Commit message: {message}')
```

2023-10-13 14:45 UTC, Anastasiia-Grishina requested changes
Great work :raised_hands:

I added one comment regarding logging the commit url. This may be interesting for faster log analysis and cherry-picking examples for the paper. If you could incorporate it, we are ready to go, from my side!

2023-10-16 14:59 UTC, Anastasiia-Grishina approved these changes

2023-10-16 15:00 UTC, Anastasiia-Grishina commented on seidr/github.py
In the interest of time, I'll do this in a separate branch :v:

2023-10-16 15:01 UTC, merged

2023-10-16 15:28 UTC, vadim0x60 commented on seidr/github.py
Looks good to me!